Reddit_Clone-master/reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs do
    resources :posts, only: [:create, :new]
  end
  resources :posts, except: [:create, :new, :index] do
    resources :comments, only: [:new]
  end
  
  resources :comments, only: [:create, :show]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Reddit_Clone-master/reddit/app/models/sub.rb
  # == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  moderator   :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :moderator, :description, presence: true
  
  belongs_to :mod,
    class_name: :User,
    foreign_key: :moderator
  
  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs
end

Reddit_Clone-master/reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login, except: [:index, :show]
  
  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end
  
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end
  
  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy!
    redirect_to subs_url
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

Reddit_Clone-master/reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit_Clone-master/reddit/app/views/subs/_form.html.erb
<form class="" action="<%= url %>" method="post">
  <%= auth_token %>
  <% if action == 'Update' %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title
    <input type="text" name="sub[title]" value="<%= subred.title %>">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="<%= subred.description %>">
  </label>
  
  <input type="submit" name="" value="<%= action %> Sub">
</form>

Reddit_Clone-master/reddit/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

Reddit_Clone-master/reddit/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

Reddit_Clone-master/reddit/app/views/subs/edit.html.erb
<%= render 'form', subred: @sub, url: sub_url, action: 'Update' %>

Reddit_Clone-master/reddit/app/views/subs/index.html.erb
<h1>ALL THE SUBS</h1>

<a href="<%= new_sub_url%>">Create a Sub</a>

<ul>
<% @subs.each do |subreddit| %>
  <li><a href="<%=sub_url(subreddit)%>"><%= subreddit.title %></a></li>
<% end %></ul>

Reddit_Clone-master/reddit/app/views/subs/new.html.erb
<%= render 'form', subred: @sub, url: subs_url, action: 'New' %>

Reddit_Clone-master/reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<% if @sub.mod == current_user %>
  <a href="<%= edit_sub_url %>">Edit Sub</a>
<% end %>
<h4 class="sub-desc">
  <p>It's a sub about <%= @sub.description %></p>
</h4>
<h6 class="sub-mod">
  <p>Created by <%= @sub.mod.username %></p>
</h6>

<ul>
  
<% @sub.posts.each do |post| %>
  <li><a href="<%= post_url(post)%>"><%=post.title%></a></li>
<% end %>
</ul>

<a href="<%= new_sub_post_url(@sub) %>">New Post</a>

Reddit_Clone-master/reddit/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>