music_app-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :destroy, :new]

  resources :bands

  resources :albums, :tracks, only: [:create, :new, :edit, :show, :update, :destroy]
end

music_app-master/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band

  has_many :tracks
end

music_app-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app-master/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums
  has_many :track, through: :albums, source: :tracks
end

music_app-master/app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

music_app-master/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_key, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password #why do we need this?
  after_initialize :ensure_session_key

  def self.find_by_credentials(user_params)
    @user = User.find_by(email: user_params[:email])
    return nil if @user.nil?

    if @user.is_password?(user_params[:password])
      return @user
    end

    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_key!
    self.session_key = SecureRandom.urlsafe_base64
    self.save!
    self.session_key
  end

  private

  def ensure_session_key
    self.session_key ||= SecureRandom.urlsafe_base64
  end
end

music_app-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :login, :user_params, :current_user

  def current_user
    # user whose session key is == session[:session key]
    @current_user ||= User.find_by(session_key: session[:session_key])
  end

  def login(user)
    session[:session_key] = user.reset_session_key!
  end

  def logged_in?
    self.session_key == session[:session_key]
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app-master/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new

  end

  def create
    @bands = Band.new(band_params)
    if @bands.save
      redirect_to bands_url
    else
      flash.now[:duped_band] = "Band already added."
      render :new
    end
  end

  def edit
  end

  def show

  end

  def update
  end

  def destroy
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(user_params)
    if @user
      @user.reset_session_key!
      login(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:creds] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    current_user.reset_session_key!
    session[:session_key] = nil
    redirect_to new_session_url
  end
end

music_app-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # render json: "Thank you for signing up!"
      login(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:error] = "Please enter a valid UN and password."
      render :new
    end
  end

  def show
    render :show
  end


end

music_app-master/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app-master/app/views/bands/index.html.erb
<h2>Bands</h2>

<a href="<%= new_band_url %>"><input type="submit" value="Add Band"></a>
<ul>
<% @bands.each do |band| %>
  <li><a href="<%= band %>"<%= band.name %></li>
<% end %>
</ul>

music_app-master/app/views/bands/new.html.erb
<%= flash.now[:duped_band] %>

<h2>Add Band</h2>
<form action="<%= bands_url %>" method="post">
  <%= render '/shared/auth_token' %>
  <label>Band
    <input type="text" name="band[name]" value="">
  </label>

  <input type="submit" value="Add Band">
</form>

music_app-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- can i add this into my css page? -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Play" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Music App</h1>
      <p class="login"> <!--  move up links and logout to upper right -->
      <% if current_user %>
        <p><a href="<%= bands_url %>"><%= current_user.email %></a></p>
        <form  action="<%= session_url %>" method="post">
          <%= render '/shared/auth_token' %>
          <input type="hidden" name="_method" value="delete">
          <input class="logout" type="submit" value="Logout">
        </form>
        <% else %>
          <a class="sign-in" href="<%= new_user_url %>">Sign Up</a>
          <a class="sign-in" href="<%= new_session_url %>">Sign In</a>
      <% end %>
      </p>
    </header>

    <br><br>

    <br><br>
    <%= yield %>
  </body>
</html>

music_app-master/app/views/shared/_auth_token.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">